Variant type storage added
UofS-Pulse-Binfo/vcf_genotypes pull request #28
Opened 2019-03-25 23:16 UTC by carolyncaron

## Metadata

 - Issue #21 

- [x] I feel this PR is ready to be merged.
- [ ] This PR is dependent upon [PR #/ nothing]

Documentation:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

## Description

Previously, there was no featureprop record for variant types which made this module incompatible with [ND Genotypes](https://github.com/UofS-Pulse-Binfo/nd_genotypes/). So in addition to implementing that functionality, I also simplified the way in which cvterms for data types were extracted and added the option to select the cvterm for variant type to the settings form.

## Dependencies

While not dependent necessarily, it is worth mentioning that Issue #15 should be tackled next to provide the user with more flexibility in selecting cvterms, as this implementation reinforces the strict requirement that variant type be selected from the feature_property CV only.

## Testing?

See PR #18 for detailed instructions on setting up this module in a cloud9 environment.

- [x] I tested on a generic Tripal Site
- [ ] I tested on a KnowPulse Clone
- [ ] This PR includes automated testing

2019-03-26 15:43 UTC, laceysanderson commented on theme/js/adminCheckCVTerms.js
> +        console.log(data);
You forgot a couple logging statements:

```suggestion
```

2019-03-26 15:43 UTC, laceysanderson commented on theme/js/adminCheckCVTerms.js
> +      console.log(url);
```suggestion
```

2019-03-26 15:44 UTC, laceysanderson commented on theme/js/adminCheckCVTerms.js
>  console.log('initial check.');
```suggestion
```

2019-03-26 15:46 UTC, laceysanderson approved these changes
Code review 👍

2019-03-29 20:33 UTC, laceysanderson approved these changes
2nd Code review looks good 👍

2019-04-05 19:51 UTC, laceysanderson requested changes
There should be two options for marker/variant type: SO term and free text description.

2019-04-05 19:51 UTC, laceysanderson commented on includes/genotypes_loader.admin.inc
> +    '#default_value' => variable_get('genotypes_featureprop_type_marker', 'marker_type'),
```suggestion
    '#default_value' => variable_get('genotypes_featureprop_type_marker', 'additionalType'),
```

2019-04-05 19:51 UTC, laceysanderson commented on includes/genotypes_loader.admin.inc
> +    '#default_value' => variable_get('genotypes_featureprop_type_variant', 'variant_type'),
```suggestion
    '#default_value' => variable_get('genotypes_featureprop_type_variant', 'additionalType'),
```

2019-04-05 19:51 UTC, laceysanderson commented on README.md
> +| Property type for free-text variant description | variant_type        | feature_property      |
```suggestion
| Property type for free-text variant description | additionalType        | schema      |
```

2019-04-05 19:51 UTC, laceysanderson commented on README.md
>  | Property type for free-text marker description | marker_type         | feature_property      |
```suggestion
| Property type for free-text marker description | additionalType         | schema      |
```

2019-04-12 16:59 UTC, laceysanderson approved these changes

2019-04-12 20:32 UTC, carolyncaron commented on includes/genotypes_loader.admin.inc
>    $feature_prop_cv = tripal_get_cv(array('name' => 'feature_property'));
```suggestion
  $feature_prop_cv = tripal_get_cv(array('name' => 'schema'));
```

2019-04-12 20:32 UTC, carolyncaron commented on includes/genotypes_loader.admin.inc
> +    '#attributes' => array('data-cv' => 'feature_property', 'data-cv_id' => $feature_prop_cv->cv_id ),
```suggestion
    '#attributes' => array('data-cv' => 'schema', 'data-cv_id' => $feature_prop_cv->cv_id ),
```

2019-04-12 20:32 UTC, carolyncaron commented on includes/genotypes_loader.admin.inc
> +  $feature_prop_cv = tripal_get_cv(array('name' => 'feature_property'));
```suggestion
  $feature_prop_cv = tripal_get_cv(array('name' => 'schema'));
```

2019-04-12 20:32 UTC, carolyncaron commented on includes/genotypes_loader.admin.inc
>      '#attributes' => array('data-cv' => 'feature_property', 'data-cv_id' => $feature_prop_cv->cv_id ),
```suggestion
    '#attributes' => array('data-cv' => 'schema', 'data-cv_id' => $feature_prop_cv->cv_id ),
```

2019-04-17 17:29 UTC, merged